[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "denali-trade"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.92.0,<1.93"
rust-std-wasm32-unknown-unknown = ">=1.92.0,<2"

[activation]
env = { RUSTFLAGS = "-C link-arg=-lc_nonshared -C linker=clang" }